[package]
name = "mariani-silver"
version = "0.1.0"
authors = ["fejx <fejx@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.81"
async-std = "1.8.0"
